"use client"

import { useEffect, useState } from "react"
import { ChevronDown, Clock3, Edit3, LockKeyhole, Save, Sparkles, Trash2 } from "lucide-react"
import { SocialActions } from "@/components/social-actions"

type ArchiveItem = { id: string; title: string; text: string; createdAt: string }
export function CreationArchive({ storageKey, label, emptyText }: { storageKey: string; label: string; emptyText: string }) { const [items, setItems] = useState<ArchiveItem[]>([]); const [openId, setOpenId] = useState<string | null>(null); const [editing, setEditing] = useState<string | null>(null); const [draft, setDraft] = useState(""); useEffect(() => { try { setItems(JSON.parse(localStorage.getItem(storageKey) || "[]")) } catch { setItems([]) } }, [storageKey]); const persist = (next: ArchiveItem[]) => { setItems(next); localStorage.setItem(storageKey, JSON.stringify(next)) }; const remove = (id: string) => persist(items.filter(item => item.id !== id)); const save = (id: string) => { persist(items.map(item => item.id === id ? { ...item, text: draft } : item)); setEditing(null) }; if (!items.length) return <section className="archive-empty"><Sparkles size={16} /><span>{emptyText}</span></section>; return <section className="creation-archive"><div className="archive-heading"><span className="eyebrow"><Clock3 size={14} /> {label}</span><span>{items.length} fragment{items.length > 1 ? "s" : ""}</span></div><div className="archive-list">{items.map(item => <article key={item.id} className={`archive-item ${openId === item.id ? "is-open" : ""}`}><button className="archive-trigger" onClick={() => setOpenId(openId === item.id ? null : item.id)} aria-expanded={openId === item.id}><span><strong>{item.title}</strong><small>{new Date(item.createdAt).toLocaleString("fr-FR", { dateStyle: "long", timeStyle: "short" })}</small></span><span className="archive-open"><LockKeyhole size={14} /> {openId === item.id ? "Refermer" : "Ouvrir"}<ChevronDown size={15} /></span></button>{openId === item.id && <div className="archive-reveal">{editing === item.id ? <><textarea className="archive-editor" value={draft} onChange={event => setDraft(event.target.value)} /><button className="archive-save" onClick={() => save(item.id)}><Save size={14} /> Enregistrer</button></> : <p>{item.text}</p>}<div className="archive-tools"><button onClick={() => { setEditing(item.id); setDraft(item.text) }}><Edit3 size={14} /> Modifier</button><button onClick={() => remove(item.id)}><Trash2 size={14} /> Supprimer</button></div><SocialActions text={item.text} title={item.title} /></div>}</article>)}</div></section> }
export function saveCreation(storageKey: string, item: Omit<ArchiveItem, "id" | "createdAt">) { const next: ArchiveItem = { ...item, id: crypto.randomUUID(), createdAt: new Date().toISOString() }; const items = JSON.parse(localStorage.getItem(storageKey) || "[]") as ArchiveItem[]; localStorage.setItem(storageKey, JSON.stringify([next, ...items].slice(0, 24))) }
