"use client"

import { MessageCircle, Heart, Share2 } from "lucide-react"
import { useState } from "react"
import { PageShell, SectionIntro } from "@/components/lunar-nav"

const posts = [{ title: "Fragile certitude", text: "Je sais que je doute, et c'est la seule chose dont je sois certain.", author: "Léa", comments: ["Cette phrase reste."] }, { title: "Joie triste", text: "J'ai souri pour ne pas déranger la tristesse.", author: "anonyme", comments: [] }, { title: "Départ immobile", text: "Je pars sans bouger, en changeant simplement de regard.", author: "Milo", comments: ["Un mouvement intérieur."] }]

export default function MesOxymPage() { const [likes, setLikes] = useState<number[]>([]); const [comment, setComment] = useState(""); const [comments, setComments] = useState<Record<number, string[]>>({}); return <PageShell><div className="feature-page social-page"><SectionIntro eyebrow="MesOxym · le fil public" title={<>Le lieu où les contradictions<br /><em>trouvent une voix.</em></>}>Fais défiler les oxymores publiés par la communauté.</SectionIntro><div className="community-feed">{posts.map((post, index) => <article className="community-card" key={post.title}><div className="community-meta"><span>{post.author}</span><span>Oxymore #{index + 1}</span></div><h2>{post.title}</h2><p>{post.text}</p><div className="community-actions"><button className={likes.includes(index) ? "is-selected" : ""} onClick={() => setLikes((current) => current.includes(index) ? current.filter((item) => item !== index) : [...current, index])}><Heart size={18} fill={likes.includes(index) ? "currentColor" : "none"} /> {likes.includes(index) ? "Aimé" : "J'aime"}</button><button><MessageCircle size={18} /> {(comments[index] ?? post.comments).length}</button><button onClick={() => navigator.clipboard?.writeText(`${post.title}\n${post.text}`)}><Share2 size={18} /> Partager</button></div><div className="comment-row"><input value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Ajouter un commentaire..." /><button className="secondary-button" onClick={() => { if (!comment.trim()) return; setComments((current) => ({ ...current, [index]: [...(current[index] ?? post.comments), comment.trim()] })); setComment("") }}>Publier</button></div>{(comments[index] ?? post.comments).map((item) => <p className="comment" key={item}>{item}</p>)}</article>)}</div></div></PageShell> }
