"use client"

import useSWR from "swr"
import { ChevronLeft, ChevronRight, Heart, MessageCircle, Send, Share2, X } from "lucide-react"
import { useState } from "react"
import { PageShell, SectionIntro } from "@/components/lunar-nav"

const fetcher = (url: string) => fetch(url).then((response) => response.json())
const networks = [{ name: "TikTok", mark: "♪", url: "https://www.tiktok.com/" }, { name: "Instagram", mark: "◎", url: "https://www.instagram.com/" }, { name: "Facebook", mark: "f", url: "https://www.facebook.com/sharer/sharer.php" }]
type Poem = { id: string; title: string; topics: string[]; text: string; author: string; likesCount: number }
type Comment = { id: string; author: string; text: string }

export default function MesOxymPage() {
  const { data: poems = [], mutate } = useSWR<Poem[]>("/api/poems", fetcher)
  const [index, setIndex] = useState(0); const [liked, setLiked] = useState<string | null>(null); const [commentsOpen, setCommentsOpen] = useState(false); const [shareOpen, setShareOpen] = useState(false); const [draft, setDraft] = useState(""); const [comments, setComments] = useState<Comment[]>([])
  const post = poems[index]
  const loadComments = async () => { if (!post) return; const response = await fetch(`/api/poems/${post.id}`); setComments(await response.json()); setCommentsOpen(true) }
  const like = async () => { if (!post || liked === post.id) return; await fetch(`/api/poems/${post.id}`, { method: "POST" }); setLiked(post.id); mutate() }
  const submit = async () => { if (!post || !draft.trim()) return; const response = await fetch(`/api/poems/${post.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: draft.trim() }) }); if (response.ok) { const comment = await response.json(); setComments((current) => [...current, comment]); setDraft("") } }
  const move = (direction: 1 | -1) => { setIndex((current) => poems.length ? (current + direction + poems.length) % poems.length : 0); setCommentsOpen(false); setShareOpen(false); setComments([]) }
  const share = (network: typeof networks[number]) => { const text = encodeURIComponent(`${post.title} — ${post.text}`); const url = network.name === "Facebook" ? `${network.url}?u=${encodeURIComponent(window.location.href)}&quote=${text}` : network.url; window.open(url, "_blank", "noopener,noreferrer"); setShareOpen(false) }
  return <PageShell><main className="feature-page social-page"><SectionIntro eyebrow="MesOxym · le fil public" title="">Retrouvez tous les poèmes ici.</SectionIntro><div className="community-feed">{post ? <article className="community-card"><div className="community-meta"><span>{post.author}</span><span>Oxymore #{index + 1}</span></div><h2>{post.title}</h2><div className="generated-topics community-topics">{post.topics.map((topic) => <span key={topic}>{topic}</span>)}</div><p className="community-poem">{post.text}</p><div className="community-actions"><button onClick={like} className={liked === post.id ? "is-liked" : ""}><Heart size={16} fill={liked === post.id ? "currentColor" : "none"} /> {post.likesCount}</button><button onClick={loadComments}><MessageCircle size={16} /> Commentaires</button><div className="share-wrap"><button onClick={() => setShareOpen(!shareOpen)}><Share2 size={16} /> Partager</button>{shareOpen && <div className="share-chooser">{networks.map((network) => <button key={network.name} onClick={() => share(network)}>{network.mark} {network.name}</button>)}</div>}</div></div>{commentsOpen && <section className="comments-panel"><div className="comments-heading"><span className="comments-title"><MessageCircle size={16} /> Commentaires</span><button onClick={() => setCommentsOpen(false)} aria-label="Fermer"><X size={16} /></button></div><div className="comments-scroll">{comments.map((comment) => <div className="comment-card" key={comment.id}><div className="comment-avatar">{comment.author.slice(0, 2).toUpperCase()}</div><div><strong>{comment.author}</strong><p>{comment.text}</p></div></div>)}</div><div className="comments-composer"><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Ajouter un commentaire..." /><button onClick={submit} aria-label="Publier le commentaire"><Send size={14} /></button></div></section>}</article> : <p className="empty-state">Aucun poème publié pour le moment.</p>}<div className="feed-navigation"><button onClick={() => move(-1)} aria-label="Poème précédent"><ChevronLeft size={18} /></button><button onClick={() => move(1)} aria-label="Poème suivant"><ChevronRight size={18} /></button></div></div></main></PageShell>
}
