"use client"

import { Heart, MessageCircle, Share2 } from "lucide-react"
import { useEffect, useState } from "react"
import { PageShell, SectionIntro } from "@/components/lunar-nav"

const basePosts = [{ title: "Fragile certitude", text: "Je sais que je doute, et c'est la seule chose dont je sois certain.", author: "Léa", comments: ["Cette phrase reste.", "Le doute comme maison."] }, { title: "Joie triste", text: "J'ai souri pour ne pas déranger la tristesse.", author: "anonyme", comments: ["Une émotion très juste."] }, { title: "Départ immobile", text: "Je pars sans bouger, en changeant simplement de regard.", author: "Milo", comments: ["Un mouvement intérieur.", "Je le garde."] }]

export default function MesOxymPage() { const [posts, setPosts] = useState(basePosts); const [likes, setLikes] = useState<number[]>([]); const [open, setOpen] = useState<number | null>(null); const [comments, setComments] = useState<Record<number, string[]>>({}); const [drafts, setDrafts] = useState<Record<number, string>>({}); useEffect(() => { const saved = localStorage.getItem("mesoxym-post"); if (saved) setPosts((current) => [{ ...JSON.parse(saved), comments: ["Une nouvelle voix dans le fil."] }, ...current]) }, []); const addComment = (index: number) => { const value = drafts[index]?.trim(); if (!value) return; setComments((current) => ({ ...current, [index]: [...(current[index] ?? posts[index].comments), value] })); setDrafts((current) => ({ ...current, [index]: "" })) }; return <PageShell><div className="feature-page social-page"><SectionIntro eyebrow="MesOxym · le fil public" title={<>Les contradictions<br /><em>trouvent une voix.</em></>}>Tes publications et celles de la communauté, dans un fil où chaque émotion peut répondre.</SectionIntro><div className="community-feed">{posts.map((post, index) => { const list = comments[index] ?? post.comments; const liked = likes.includes(index); return <article className="community-card" key={`${post.title}-${index}`}><div className="community-meta"><span>{post.author}</span><span>Oxymore #{index + 1}</span></div><h2>{post.title}</h2><p>{post.text}</p><div className="community-actions"><button className={liked ? "is-selected" : ""} onClick={() => setLikes((current) => liked ? current.filter((item) => item !== index) : [...current, index])} title="J'aime"><Heart size={18} fill={liked ? "currentColor" : "none"} /> {liked ? "Aimé" : "J'aime"}</button><button className={open === index ? "is-selected" : ""} onClick={() => setOpen(open === index ? null : index)} title="Commentaires"><MessageCircle size={18} /> {list.length}</button><button onClick={() => navigator.clipboard?.writeText(`${post.title}\n${post.text}`)} title="Partager"><Share2 size={18} /> Partager</button></div>{open === index && <div className="comment-drawer"><div>{list.map((item) => <p className="comment" key={item}>{item}</p>)}</div><div className="comment-row"><input value={drafts[index] ?? ""} onChange={(event) => setDrafts((current) => ({ ...current, [index]: event.target.value }))} onKeyDown={(event) => { if (event.key === "Enter" && !event.nativeEvent.isComposing) addComment(index) }} placeholder="Ajouter un commentaire..." /><button className="secondary-button" onClick={() => addComment(index)}>Publier</button></div></div>}</article> })}</div></div></PageShell> }
